In [34]:
import torch

In [35]:
# 张量tensor表示一个数值组成的数组 这个数组可能有多个维度
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
# shape记录了张量的形状
x.shape

torch.Size([12])

In [37]:
# 元素个数
x.numel()

12

In [38]:
# 改变形状
x = x.reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [39]:
torch.zeros((2 , 3 , 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [40]:
torch.ones((2 , 3 , 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [41]:
# 连接张量
X = torch.arange(12 , dtype=torch.float32).reshape((3 , 4))
Y = torch.tensor([[2.0 , 1 , 4 , 3] , [1 , 2 , 3 , 4] , [4 , 3 , 2 , 1]])

# 在第0维和第1维 合并X , Y
torch.cat((X , Y) , dim=0) , torch.cat((X , Y) , dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [42]:
# 按逻辑运算符返回张量 这里事实上有运算符重载
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [43]:
X.sum() # 返回只有一个元素的标量

tensor(66.)

In [44]:
# 广播
a = torch.arange(3).reshape((3 , 1))
b = torch.arange(2).reshape((1 , 2))
# a b 都是二维张量 在计算时会发生维度对齐
a , b , a + b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

In [45]:
# 按维度求和
A = torch.arange(40 , dtype=torch.float32).reshape(2 , 5 , 4)
A , A.shape , A.sum()

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 torch.Size([2, 5, 4]),
 tensor(780.))

In [46]:
# 按某个维度求和 就会将那个维度值变为1 即消去那个维度
A_sum_axis0 = A.sum(axis = 0)
A_sum_axis0 , A_sum_axis0.shape

(tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]),
 torch.Size([5, 4]))

In [47]:
A_sum_axis1 = A.sum(axis = 1)
A_sum_axis1 , A_sum_axis0.shape

(tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]]),
 torch.Size([5, 4]))

In [48]:
A.sum(axis=[0 , 1])

tensor([180., 190., 200., 210.])

In [49]:
sum_A = A.sum(axis=1 , keepdim=True)
sum_A 

tensor([[[ 40.,  45.,  50.,  55.]],

        [[140., 145., 150., 155.]]])

In [50]:
# 广播 A / sum_A
A / sum_A

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

In [51]:
A.mean()

tensor(19.5000)

In [52]:
# l2 范数 向量元素平方和的平方根
u = torch.tensor([3.0 , -4.0])
torch.norm(u)

tensor(5.)

In [53]:
# l1 范数 向量的绝对值之和
torch.abs(u).sum()

tensor(7.)

In [54]:
# 矩阵的F范数 矩阵元素平方和的平方根
torch.norm(torch.ones(4 , 9))

tensor(6.)